USE master;
GO

IF DB_ID('DORM') IS NOT NULL
BEGIN
    ALTER DATABASE DORM SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE DORM;
END
GO

CREATE DATABASE DORM;
GO

USE DORM;
GO

CREATE TABLE TAI_KHOAN (
    MA_TK VARCHAR(5) PRIMARY KEY,
    MAT_KHAU VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(150),
    ROLE VARCHAR(20)
);

CREATE TABLE NHAN_VIEN
(
    MA_NV VARCHAR(5) PRIMARY KEY, 
    TEN_NV NVARCHAR(250) NOT NULL, 
    NGAY_SINH DATE CHECK (NGAY_SINH < GETDATE()), 
    NGAY_BD_LAM DATE CHECK (NGAY_BD_LAM < GETDATE()), 
    CCCD VARCHAR(12) NOT NULL, 
    SDT VARCHAR(11) NOT NULL, 
	MA_TK VARCHAR(5) NULL UNIQUE, 
    GIOI_TINH NVARCHAR(3) CONSTRAINT CHK_GIOITINH_NV CHECK (GIOI_TINH IN (N'Nữ', N'Nam')),
    CHUC_VU NVARCHAR(100) CONSTRAINT CHK_CHUCVU_NV CHECK (CHUC_VU IN (N'Quản lý', N'Sale')),
    CONSTRAINT CHK_LOGIC_NGAY_NV CHECK (NGAY_SINH < NGAY_BD_LAM),
	CONSTRAINT FK_NHANVIEN_MATK FOREIGN KEY (MA_TK) REFERENCES TAI_KHOAN(MA_TK)
);

CREATE TABLE KHACH_HANG
(
    MA_KH VARCHAR(5) PRIMARY KEY, 
    TEN_KH NVARCHAR(250) NOT NULL, 
    NGAY_SINH DATE CHECK (NGAY_SINH < GETDATE()), 
    CCCD VARCHAR(12) NOT NULL, 
    SDT VARCHAR(11) NOT NULL, 
    GIOI_TINH NVARCHAR(3) CONSTRAINT CHK_GIOITINH_KH CHECK (GIOI_TINH IN (N'Nữ', N'Nam')), 
	MA_TK VARCHAR(5) NULL,
	CONSTRAINT FK_KHACHHANG_MATK FOREIGN KEY (MA_TK) REFERENCES TAI_KHOAN(MA_TK)
);


CREATE TABLE PHIEU_DANG_KY_THUE
(
	MA_PDK VARCHAR(5) PRIMARY KEY, 
	NGAY_DANG_KY DATE CHECK (NGAY_DANG_KY < GETDATE()),
	MA_NV VARCHAR(5),
	MA_KH VARCHAR(5),
	HINH_THUC_THUE NVARCHAR(25) CHECK (HINH_THUC_THUE IN (N'Nhóm', N'Cá nhân')),
	CONSTRAINT FK_PDKT_MANV FOREIGN KEY (MA_NV) REFERENCES NHAN_VIEN(MA_NV),
	CONSTRAINT FK_PDKT_MAKH FOREIGN KEY (MA_KH) REFERENCES KHACH_HANG(MA_KH),
);

CREATE TABLE PHIEU_DAT_COC
(
	MA_PDC VARCHAR(5) PRIMARY KEY,
	NGAY DATE CHECK (NGAY < GETDATE()),
	SO_TIEN INT CHECK (SO_TIEN > 0),
	TRANG_THAI NVARCHAR(100) CHECK (TRANG_THAI IN (N'Đã đặt cọc', N'Chưa đặt cọc')),
	MA_KH VARCHAR(5),
	MA_NV VARCHAR(5),
	CONSTRAINT FK_PDC_MANV FOREIGN KEY (MA_NV) REFERENCES NHAN_VIEN(MA_NV),
	CONSTRAINT FK_PDC_MAKH FOREIGN KEY (MA_KH) REFERENCES KHACH_HANG(MA_KH)
);

CREATE TABLE CHINH_SACH_THUE
(
	MA_DIEU_KHOAN VARCHAR(5) PRIMARY KEY,
	TEN_DIEU_KHOAN NVARCHAR(150) NOT NULL, 
	NOI_DUNG NVARCHAR(500)
);

CREATE TABLE KY_TUC_XA
(
	MA_KTX VARCHAR(6) PRIMARY KEY, 
	TEN_KTX NVARCHAR(150) NOT NULL, 
	DIA_CHI NVARCHAR(500) NOT NULL, 
	QUY_DINH NVARCHAR(500), 
	MA_DIEU_KHOAN VARCHAR(5),
	CONSTRAINT FK_KTX_MADIEUKHOAN FOREIGN KEY (MA_DIEU_KHOAN) REFERENCES CHINH_SACH_THUE(MA_DIEU_KHOAN)
);

CREATE TABLE PHONG (
    MA_PHONG VARCHAR(4) PRIMARY KEY,
    IMAGE_URL VARCHAR(255),
    SL_GIUONG INT CHECK (SL_GIUONG > 0),
    SL_GIUONG_TRONG INT CHECK (SL_GIUONG_TRONG >= 0),
    TRANG_THAI NVARCHAR(10) CHECK (TRANG_THAI IN (N'Đã thuê', N'Trống')),
    MA_KTX VARCHAR(6),

    TEN_PHONG NVARCHAR(100),
    GIA_DIEN INT,
    GIA_NUOC INT,
    WIFI NVARCHAR(50),
    GUI_XE INT,
    DICH_VU INT,

    CONSTRAINT FK_PHONG_MAKTX FOREIGN KEY (MA_KTX) REFERENCES KY_TUC_XA(MA_KTX),
    CONSTRAINT CHK_PHONG_SLT CHECK (SL_GIUONG_TRONG <= SL_GIUONG)
);

CREATE TABLE GIUONG 
(
	MA_GIUONG VARCHAR(5) PRIMARY KEY, 
	TRANG_THAI NVARCHAR(10) CHECK (TRANG_THAI IN (N'Đã thuê', N'Trống')),
	GIA INT CHECK (GIA > 0),
	MA_PHONG VARCHAR(4),
	CONSTRAINT FK_GIUONG_MAPHONG FOREIGN KEY (MA_PHONG) REFERENCES PHONG(MA_PHONG)
);

CREATE TABLE LICH
(
	MA_PHIEU VARCHAR(5) PRIMARY KEY, 
	NGAY DATE CHECK (NGAY < GETDATE()),
	LOAI NVARCHAR(14) CHECK (LOAI IN (N'Xem phòng', N'Nhận phòng', N'Bàn giao phòng')),
	TRANG_THAI NVARCHAR(20) CHECK (TRANG_THAI IN (N'Đã xử lý',N'Chưa xử lý')),
	MA_PDK VARCHAR(5) NULL,
	MA_PDC VARCHAR(5) NULL,
	MA_KTX VARCHAR(6) NULL,
	MA_PHONG VARCHAR(4) NULL,
	CONSTRAINT FK_LICH_MAPDK FOREIGN KEY (MA_PDK) REFERENCES PHIEU_DANG_KY_THUE(MA_PDK),
	CONSTRAINT FK_LICH_MAPDC FOREIGN KEY (MA_PDC) REFERENCES PHIEU_DAT_COC(MA_PDC),
	CONSTRAINT FK_LICH_MAKTX FOREIGN KEY (MA_KTX) REFERENCES KY_TUC_XA(MA_KTX),
	CONSTRAINT FK_LICH_MAPHONG FOREIGN KEY (MA_PHONG) REFERENCES PHONG(MA_PHONG),
);

CREATE TABLE LICH_GIUONG
(
	MA_PHIEU VARCHAR(5), 
	MA_GIUONG VARCHAR(5), 
	PRIMARY KEY (MA_PHIEU, MA_GIUONG)
)

CREATE TABLE HOP_DONG_THUE (
    MA_HOP_DONG VARCHAR(5) PRIMARY KEY,
    NGAY_BD DATE CHECK (NGAY_BD <= GETDATE()),
    NGAY_KT DATE CHECK (NGAY_KT > GETDATE()),
    SL_NGUOI_THUE INT CHECK (SL_NGUOI_THUE > 0),
    NOI_DUNG NVARCHAR(1000),
    TRANG_THAI NVARCHAR(10) CHECK (TRANG_THAI IN (N'Đã ký', N'Chưa ký')),
    MA_PHIEU VARCHAR(5),

    IMAGE_URL VARCHAR(255),

    CONSTRAINT FK_HOPDONGTHUE_MAPHIEU FOREIGN KEY (MA_PHIEU) REFERENCES LICH(MA_PHIEU)
);

CREATE TABLE BIEN_BAN_BAN_GIAO (
    MA_BAN_GIAO VARCHAR(5) PRIMARY KEY,
    NGAY DATE CHECK (NGAY <= GETDATE()),
    MA_HOP_DONG VARCHAR(5),
    MA_NV VARCHAR(5),

    IMAGE_URL VARCHAR(255),

    CONSTRAINT FK_BIENBANBANGIAO_MAHOPDONG FOREIGN KEY (MA_HOP_DONG) REFERENCES HOP_DONG_THUE(MA_HOP_DONG),
    CONSTRAINT FK_BIENBANBANGIAO_MANV FOREIGN KEY (MA_NV) REFERENCES NHAN_VIEN(MA_NV)
);

CREATE TABLE BB_BG_CHI_TIET
(
	MA_VT VARCHAR(5) PRIMARY KEY, 
	TEN_VAT_TU NVARCHAR(100) NOT NULL, 
	SO_LUONG INT CHECK (SO_LUONG > 0),
	GIA_TRI INT CHECK (GIA_TRI > 0), 
	MA_BAN_GIAO VARCHAR(5),
	CONSTRAINT FK_BBBGCHITIET_MABANGIAO FOREIGN KEY (MA_BAN_GIAO) REFERENCES BIEN_BAN_BAN_GIAO(MA_BAN_GIAO)
);

CREATE TABLE PHIEU_THANH_TOAN
(
	MA_THANH_TOAN VARCHAR(5) PRIMARY KEY, 
	HINH_THUC NVARCHAR(10) CHECK (HINH_THUC IN (N'Tiền mặt', N'QR')),
	NGAY DATE CHECK (NGAY <= GETDATE()),
	SO_TIEN INT CHECK (SO_TIEN > 0), 
	TRANG_THAI NVARCHAR(20) CHECK (TRANG_THAI IN (N'Đã thanh toán', N'Chưa thanh toán')),
	MA_HOP_DONG VARCHAR(5) NULL,
	MA_PDC VARCHAR(5) NULL, 
	CONSTRAINT FK_PHIEUTHANHTOAN_MAHOPDONG FOREIGN KEY (MA_HOP_DONG) REFERENCES HOP_DONG_THUE(MA_HOP_DONG),
	CONSTRAINT FK_PHIEUTHANHTOAN_MAPDC FOREIGN KEY (MA_PDC) REFERENCES PHIEU_DAT_COC(MA_PDC)
);

CREATE TABLE BIEN_BAN_TRA_PHONG
(
	MA_BB_TRA_PHONG VARCHAR(5) PRIMARY KEY, 
	NGAY DATE CHECK (NGAY <= GETDATE()),
	NOI_DUNG NVARCHAR(500),
	MA_NV VARCHAR(5),
	MA_THANH_TOAN VARCHAR(5), 
	MA_HOP_DONG VARCHAR(5),
	TRANG_THAI NVARCHAR(20) CHECK (TRANG_THAI IN (N'Đã hẹn', N'Đang chờ xử lí', N'Đã xử lí')),
	CONSTRAINT FK_BIENBANTRAPHONG_MANV FOREIGN KEY (MA_NV) REFERENCES NHAN_VIEN(MA_NV),
	CONSTRAINT FK_BIENBANTRAPHONG_MATHANHTOAN FOREIGN KEY (MA_THANH_TOAN) REFERENCES PHIEU_THANH_TOAN(MA_THANH_TOAN),
	CONSTRAINT FK_BIENBANTRAPHONG_MAHOPDONG FOREIGN KEY (MA_HOP_DONG) REFERENCES HOP_DONG_THUE(MA_HOP_DONG)
);

GO
--số lượng người thuê <= tổng số lượng giường của phòng
CREATE TRIGGER TRG_Check_SL_NguoiThue
ON HOP_DONG_THUE
AFTER INSERT, UPDATE
AS
BEGIN
    IF EXISTS (
        SELECT 1
        FROM inserted i
        JOIN LICH l ON i.MA_PHIEU = l.MA_PHIEU
        JOIN PHONG p ON l.MA_PHONG = p.MA_PHONG
        WHERE i.SL_NGUOI_THUE > p.SL_GIUONG
    )
    BEGIN
        RAISERROR (N'Lỗi: Số lượng người thuê vượt quá tổng số giường của phòng!', 16, 1);
        ROLLBACK TRANSACTION;
    END
END;
GO

INSERT INTO TAI_KHOAN (MA_TK, MAT_KHAU, EMAIL, ROLE) VALUES
('TK001', '123456', 'vy@gmail.com', 'CUSTOMER'),
('TK002', '123456', 'nv@gmail.com', 'SALE');
INSERT INTO NHAN_VIEN VALUES
('NV001', N'Nguyễn Văn A', '1995-01-01', '2020-01-01',
 '123456789012', '0900000001', 'TK002', N'Nam', N'Quản lý');
 INSERT INTO KHACH_HANG VALUES
('KH001', N'Khưu Ngọc Ý Vy', '2000-05-01',
 '098765432112', '0987654321', N'Nữ', 'TK001');
 INSERT INTO CHINH_SACH_THUE VALUES
('CS001', N'Nội quy chung', N'Không gây ồn, giữ vệ sinh');
INSERT INTO KY_TUC_XA VALUES
('KTX001', N'Ký túc xá Chợ Quán', N'Q5 TP.HCM',
 N'Nội quy nghiêm ngặt', 'CS001');
 INSERT INTO PHONG (
    MA_PHONG, IMAGE_URL, SL_GIUONG, SL_GIUONG_TRONG,
    TRANG_THAI, MA_KTX,
    TEN_PHONG, GIA_DIEN, GIA_NUOC, WIFI, GUI_XE, DICH_VU
)
VALUES (
    'P201',
    'https://example.com/phong.jpg',
    6,
    2,
    N'Trống',
    'KTX001',
    N'Phòng Deluxe',
    3500,
    15000,
    N'Miễn phí',
    100000,
    200000
);
INSERT INTO GIUONG VALUES
('G001', N'Trống', 1500000, 'P201'),
('G002', N'Trống', 1500000, 'P201'),
('G003', N'Đã thuê', 1500000, 'P201'),
('G004', N'Trống', 1500000, 'P201'),
('G005', N'Trống', 1500000, 'P201'),
('G006', N'Trống', 1500000, 'P201');
INSERT INTO PHIEU_DANG_KY_THUE VALUES
('PDK01', GETDATE()-1, 'NV001', 'KH001', N'Cá nhân');
INSERT INTO PHIEU_DAT_COC VALUES
('PDC01', GETDATE()-1, 500000, N'Đã đặt cọc', 'KH001', 'NV001');
INSERT INTO LICH VALUES
('L001', GETDATE()-1, N'Nhận phòng', N'Chưa xử lý',
 'PDK01', 'PDC01', 'KTX001', 'P201');
INSERT INTO HOP_DONG_THUE VALUES
('HD001', GETDATE()-1, GETDATE()+30, 2,
 N'Hợp đồng thuê phòng', N'Chưa ký',
 'L001',
 'https://example.com/hopdong.jpg');
 INSERT INTO BIEN_BAN_BAN_GIAO VALUES
('BB001', GETDATE(), 'HD001', 'NV001',
 'https://example.com/bienban.jpg');
INSERT INTO BB_BG_CHI_TIET VALUES
('VT001', N'Giường', 2, 2000000, 'BB001'),
('VT002', N'Bàn', 1, 500000, 'BB001');
