USE MASTER
GO
DROP DATABASE DORM
GO

CREATE DATABASE DORM
GO
USE DORM
GO

/* =========================================================
   1. BẢNG ĐỘC LẬP (không phụ thuộc FK)
========================================================= */

CREATE TABLE CHINH_SACH_THUE
(
    MA_DIEU_KHOAN VARCHAR(5) PRIMARY KEY,
    TEN_DIEU_KHOAN NVARCHAR(150) NOT NULL,
    NOI_DUNG NVARCHAR(500)
);

CREATE TABLE HOP_DONG_THUE
(
    MA_HOP_DONG VARCHAR(10) PRIMARY KEY,
    NGAY_BD DATE CHECK (NGAY_BD <= CAST(GETDATE() AS DATE)),
    NGAY_KT DATE,
    SL_NGUOI_THUE INT CHECK (SL_NGUOI_THUE > 0),
    NOI_DUNG NVARCHAR(1000),
    TRANG_THAI NVARCHAR(10)
        CHECK (TRANG_THAI IN (N'Đã ký', N'Chưa ký')),
        CHECK (TRANG_THAI IN (N'Đã ký', N'Chưa ký')),
    MA_PHIEU VARCHAR(10),
    IMAGE_URL VARCHAR(255)
);

/* =========================================================
   2. KTX → PHÒNG → GIƯỜNG
========================================================= */

CREATE TABLE KY_TUC_XA
(
    MA_KTX VARCHAR(6) PRIMARY KEY,
    TEN_KTX NVARCHAR(150) NOT NULL,
    DIA_CHI NVARCHAR(500) NOT NULL,
    QUY_DINH NVARCHAR(500),
    MA_DIEU_KHOAN VARCHAR(5),

    GIA_DIEN INT,
    GIA_NUOC INT,
    WIFI NVARCHAR(50),
    GUI_XE INT,
    DICH_VU INT,

    CONSTRAINT FK_KTX_MADIEUKHOAN
        FOREIGN KEY (MA_DIEU_KHOAN)
        REFERENCES CHINH_SACH_THUE(MA_DIEU_KHOAN)
);

CREATE TABLE PHONG
(
    MA_KTX VARCHAR(6),
    MA_PHONG VARCHAR(10),
    IMAGE_URL VARCHAR(255),

    SL_GIUONG INT CHECK (SL_GIUONG > 0),
    SL_GIUONG_TRONG INT CHECK (SL_GIUONG_TRONG >= 0),
    TRANG_THAI NVARCHAR(10)
        CHECK (TRANG_THAI IN (N'Đã thuê', N'Trống')),

    SO_DIEN_CU INT CHECK (SO_DIEN_CU >= 0),
    SO_DIEN_MOI INT CHECK (SO_DIEN_MOI >= 0),

    MO_TA NVARCHAR(255),

    PRIMARY KEY (MA_KTX, MA_PHONG),

    CONSTRAINT FK_PHONG_MAKTX
        FOREIGN KEY (MA_KTX)
        REFERENCES KY_TUC_XA(MA_KTX),

    CONSTRAINT CHK_PHONG_SLT
        CHECK (SL_GIUONG_TRONG <= SL_GIUONG),

    CONSTRAINT CHK_PHONG_SODIEN
        CHECK (SO_DIEN_MOI >= SO_DIEN_CU)
);

CREATE TABLE GIUONG
(
    MA_KTX VARCHAR(6),
    MA_PHONG VARCHAR(10),
    MA_GIUONG VARCHAR(10),

    TRANG_THAI NVARCHAR(10)
        CHECK (TRANG_THAI IN (N'Đã thuê', N'Trống')),

    GIA INT CHECK (GIA > 0),

    PRIMARY KEY (MA_KTX, MA_PHONG, MA_GIUONG),

    CONSTRAINT FK_GIUONG_MAPHONG
        FOREIGN KEY (MA_KTX, MA_PHONG)
        REFERENCES PHONG(MA_KTX, MA_PHONG)
);

/* =========================================================
   3. TÀI KHOẢN → NHÂN VIÊN / KHÁCH HÀNG
========================================================= */

CREATE TABLE TAI_KHOAN
(
    MA_TK VARCHAR(5) PRIMARY KEY,
    MAT_KHAU VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(150),



    ROLE VARCHAR(20)
        CHECK (ROLE IN ('SALE', 'BRANCH_MANAGER', 'CUSTOMER')),

    MA_HOP_DONG VARCHAR(10) NULL,
	CONSTRAINT FK_TK_MAHOPDONG FOREIGN KEY(MA_HOP_DONG) REFERENCES HOP_DONG_THUE(MA_HOP_DONG)
	);

CREATE TABLE NHAN_VIEN
(
    MA_NV VARCHAR(5) PRIMARY KEY,
    TEN_NV NVARCHAR(250) NOT NULL,

    NGAY_SINH DATE CHECK (NGAY_SINH < CAST(GETDATE() AS DATE)),
    NGAY_BD_LAM DATE CHECK (NGAY_BD_LAM <= CAST(GETDATE() AS DATE)),

    CCCD VARCHAR(12) NOT NULL,
    SDT VARCHAR(11) NOT NULL,

    MA_TK VARCHAR(5) NULL UNIQUE,

    GIOI_TINH NVARCHAR(3)
        CHECK (GIOI_TINH IN (N'Nữ', N'Nam')),

    CHUC_VU NVARCHAR(100)
        CHECK (CHUC_VU IN (N'Quản lý', N'Sale')),

    CONSTRAINT CHK_LOGIC_NGAY_NV
        CHECK (NGAY_SINH < NGAY_BD_LAM),

    CONSTRAINT FK_NHANVIEN_MATK
        FOREIGN KEY (MA_TK)
        REFERENCES TAI_KHOAN(MA_TK)
    
    
);

CREATE TABLE KHACH_HANG
(
    MA_KH VARCHAR(5) PRIMARY KEY,
    TEN_KH NVARCHAR(250) NOT NULL,

    NGAY_SINH DATE CHECK (NGAY_SINH < CAST(GETDATE() AS DATE)),

    CCCD VARCHAR(12) NOT NULL,
    SDT VARCHAR(11) NOT NULL,

    GIOI_TINH NVARCHAR(3)
        CHECK (GIOI_TINH IN (N'Nữ', N'Nam')),

    MA_TK VARCHAR(5) NULL,

    CONSTRAINT FK_KHACHHANG_MATK
        FOREIGN KEY (MA_TK)
        REFERENCES TAI_KHOAN(MA_TK)
);
/* =========================================================
   4. PHIẾU ĐĂNG KÝ / ĐẶT CỌC
========================================================= */

CREATE TABLE PHIEU_DANG_KY_THUE
(
    MA_PDK VARCHAR(10) PRIMARY KEY,
    NGAY_DANG_KY DATE
        CHECK (NGAY_DANG_KY <= CAST(GETDATE() AS DATE)),
    MA_KH VARCHAR(5),
    HINH_THUC_THUE NVARCHAR(25)
        CHECK (HINH_THUC_THUE IN (N'Nhóm', N'Cá nhân')),
    CONSTRAINT FK_PDKT_MAKH
        FOREIGN KEY (MA_KH)
        REFERENCES KHACH_HANG(MA_KH)
);

CREATE TABLE PHIEU_DAT_COC
(
    MA_PDC VARCHAR(10) PRIMARY KEY,
    NGAY DATETIME NOT NULL,

    SO_TIEN INT CHECK (SO_TIEN > 0),

    TRANG_THAI NVARCHAR(100)
        CHECK (TRANG_THAI IN (N'Đã đặt cọc', N'Chưa đặt cọc')),

    MA_KH VARCHAR(5),
    MA_NV VARCHAR(5),

    CONSTRAINT FK_PDC_MANV
        FOREIGN KEY (MA_NV)
        REFERENCES NHAN_VIEN(MA_NV),

    CONSTRAINT FK_PDC_MAKH
        FOREIGN KEY (MA_KH)
        REFERENCES KHACH_HANG(MA_KH)
);

/* =========================================================
   5. LỊCH
========================================================= */

CREATE TABLE LICH
(
    MA_PHIEU VARCHAR(10) PRIMARY KEY,

    NGAY_GIO DATETIME, 

    LOAI NVARCHAR(50)
        CHECK (LOAI IN (
            N'Xem phòng',
            N'Nhận phòng',
            N'Bàn giao phòng'
        )),

    TRANG_THAI NVARCHAR(20)
        CHECK (TRANG_THAI IN (
            N'Đã xử lý',
            N'Chưa xử lý'
        )),

    MA_PDK VARCHAR(10) NULL,
    MA_PDC VARCHAR(10) NULL,

    MA_KTX VARCHAR(6),
    MA_PHONG VARCHAR(10),
    MA_NV VARCHAR(5) NULL,

    CONSTRAINT FK_LICH_MAPDK
        FOREIGN KEY (MA_PDK)
        REFERENCES PHIEU_DANG_KY_THUE(MA_PDK),

    CONSTRAINT FK_LICH_MAPDC
        FOREIGN KEY (MA_PDC)
        REFERENCES PHIEU_DAT_COC(MA_PDC),

    CONSTRAINT FK_LICH_MAKTX
        FOREIGN KEY (MA_KTX)
        REFERENCES KY_TUC_XA(MA_KTX),

    CONSTRAINT FK_LICH_MAPHONG
        FOREIGN KEY (MA_KTX, MA_PHONG)
        REFERENCES PHONG(MA_KTX, MA_PHONG),

    CONSTRAINT FK_LICH_MANV
        FOREIGN KEY (MA_NV)
        REFERENCES NHAN_VIEN(MA_NV)
    
    
);

CREATE TABLE LICH_GIUONG
(
    MA_PHIEU VARCHAR(10),
    MA_GIUONG VARCHAR(10),

    PRIMARY KEY (MA_PHIEU, MA_GIUONG),

    CONSTRAINT FK_LICHGIUONG_LICH
        FOREIGN KEY (MA_PHIEU)
        REFERENCES LICH(MA_PHIEU)
);

/* =========================================================
   6. FK thêm cho HỢP ĐỒNG + TÀI KHOẢN
========================================================= */

ALTER TABLE HOP_DONG_THUE
ADD CONSTRAINT FK_HOPDONGTHUE_MAPHIEU
FOREIGN KEY (MA_PHIEU)
REFERENCES LICH(MA_PHIEU);




/* =========================================================
   7. CÁC BẢNG SAU HỢP ĐỒNG
========================================================= */

CREATE TABLE BIEN_BAN_BAN_GIAO
(
    MA_BAN_GIAO VARCHAR(10) PRIMARY KEY,
    NGAY DATE CHECK (NGAY <= CAST(GETDATE() AS DATE)),
    MA_HOP_DONG VARCHAR(10),
    MA_NV VARCHAR(5),

    IMAGE_URL VARCHAR(255),

    CONSTRAINT FK_BIENBANBANGIAO_MAHOPDONG
        FOREIGN KEY (MA_HOP_DONG)
        REFERENCES HOP_DONG_THUE(MA_HOP_DONG),

    CONSTRAINT FK_BIENBANBANGIAO_MANV
        FOREIGN KEY (MA_NV)
        REFERENCES NHAN_VIEN(MA_NV)
    
    
);

CREATE TABLE BB_BG_CHI_TIET
(
    MA_VT VARCHAR(10) PRIMARY KEY,
    TEN_VAT_TU NVARCHAR(100) NOT NULL,

    SO_LUONG INT CHECK (SO_LUONG > 0),
    GIA_TRI INT CHECK (GIA_TRI > 0),

    MA_BAN_GIAO VARCHAR(10),

    CONSTRAINT FK_BBBGCHITIET_MABANGIAO
        FOREIGN KEY (MA_BAN_GIAO)
        REFERENCES BIEN_BAN_BAN_GIAO(MA_BAN_GIAO)
    
    
);

CREATE TABLE PHIEU_THANH_TOAN
(
    MA_THANH_TOAN VARCHAR(5) PRIMARY KEY,

    HINH_THUC NVARCHAR(50)
        CHECK (HINH_THUC IN (N'Tiền mặt', N'QR')),

    NGAY DATE CHECK (NGAY <= CAST(GETDATE() AS DATE)),

    SO_TIEN INT CHECK (SO_TIEN > 0),

    TRANG_THAI NVARCHAR(20)
        CHECK (TRANG_THAI IN (
            N'Đã thanh toán',
            N'Chưa thanh toán'
        )),

    MA_HOP_DONG VARCHAR(10) NULL,
    MA_PDC VARCHAR(10) NULL,

    CONSTRAINT FK_PHIEUTHANHTOAN_MAHOPDONG
        FOREIGN KEY (MA_HOP_DONG)
        REFERENCES HOP_DONG_THUE(MA_HOP_DONG),

    CONSTRAINT FK_PHIEUTHANHTOAN_MAPDC
        FOREIGN KEY (MA_PDC)
        REFERENCES PHIEU_DAT_COC(MA_PDC)
    
    
);

CREATE TABLE BIEN_BAN_TRA_PHONG
(
    MA_BB_TRA_PHONG VARCHAR(6) PRIMARY KEY,

    NGAY DATE CHECK (NGAY <= CAST(GETDATE() AS DATE)),
    NOI_DUNG NVARCHAR(500),

    MA_NV VARCHAR(5),
    MA_THANH_TOAN VARCHAR(5),
    MA_HOP_DONG VARCHAR(10),

    TRANG_THAI NVARCHAR(20)
        CHECK (TRANG_THAI IN (
            N'Đã hẹn',
            N'Đang chờ xử lí',
            N'Đã xử lí'
        )),

    CONSTRAINT FK_BIENBANTRAPHONG_MANV
        FOREIGN KEY (MA_NV)
        REFERENCES NHAN_VIEN(MA_NV),

    CONSTRAINT FK_BIENBANTRAPHONG_MATHANHTOAN
        FOREIGN KEY (MA_THANH_TOAN)
        REFERENCES PHIEU_THANH_TOAN(MA_THANH_TOAN),

    CONSTRAINT FK_BIENBANTRAPHONG_MAHOPDONG
        FOREIGN KEY (MA_HOP_DONG)
        REFERENCES HOP_DONG_THUE(MA_HOP_DONG)
    
    
);

GO



/* =========================================================
   8. TRIGGER
========================================================= */
CREATE TRIGGER TRG_Check_SL_NguoiThue
ON HOP_DONG_THUE
AFTER INSERT, UPDATE
AS
BEGIN
    IF EXISTS
    (
        SELECT 1
        FROM inserted i
        JOIN LICH l
            ON i.MA_PHIEU = l.MA_PHIEU
        JOIN PHONG p
            ON l.MA_KTX = p.MA_KTX
           AND l.MA_PHONG = p.MA_PHONG
        WHERE i.SL_NGUOI_THUE > p.SL_GIUONG
    )
    BEGIN
        RAISERROR
        (
            N'Lỗi: Số lượng người thuê vượt quá tổng số giường của phòng!',
            16,
            1
        );

        ROLLBACK TRANSACTION;
    END
END;
GO